### ISSUE TITLE
part of

### ISSUE THREAD

**Issue by Vithanco** [nabil6391/graphview#59]
Hi There! 
Dart beginner problem most likely...

I followed the installation guidelines, but get this error:
```
Error: Can't import '../../flutter/.pub-cache/hosted/pub.dartlang.org/graphview-1.1.0/lib/Algorithm.dart', because
it has a 'part of' declaration.
```
Is the installation guideline out of date?

I added dependency like this:
```
dependencies:
  flutter:
    sdk: flutter

  graphview: ^1.1.0
```

Thanks!
Klaus
